[package]
name = "bevy-physics-weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.19.0-rc.2", default-features = false, features = ["3d", "free_camera"] }
# bevy_flycam = "0.18.0"  # not yet compatible with 0.19
bevy_mesh = "0.19.0-rc.2"
physics = { path = "physics" }
