[package]
name = "bevy-physics-weekend"
version = "0.1.0"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
bevy_flycam = "0.4.0"
# bevy_fly_camera = "0.6.0"
# glam = { git = "http://github.com/bitshifter/glam-rs" }

[patch.crates-io]
bevy = { git = "http://github.com/bitshifter/bevy", branch = "latest+glam-git" }
