[package]
name = "physics"
version = "0.1.0"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

[dependencies]
# glam = "0.13.0"
glam = { git = "https://github.com/bitshifter/glam-rs", features = ["serde", "debug-glam-assert"] }
serde = "1.0"
serde_json = "1.0"
